apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.4.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: mariadb-service
          - name: WORDPRESS_DB_NAME
            value: wordpress
          - name: WORDPRESS_DB_USER
            value: wordpress
          - name: WORDPRESS_DB_PASSWORD
            value: wordpress
        volumeMounts:
          - name: wordpress-html
            mountPath: /var/www/html
      volumes:
        - name: wordpress-html
          persistentVolumeClaim:
            claimName: wordpress-pvc
