apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb 
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: wordpress
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-mysql
        persistentVolumeClaim:
          claimName: mariadb-pvc
