apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: {{.Values.wordpress.replicas}}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: {{.Values.wordpress.image.repository}}:{{.Values.wordpress.image.tag}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: {{.Values.wordpress.wp_db_host}}
          - name: WORDPRESS_DB_NAME
            value: {{.Values.mariadb.mysql_database}}
          - name: WORDPRESS_DB_USER
            value: {{.Values.mariadb.mysql_user}}
          - name: WORDPRESS_DB_PASSWORD
            value: {{.Values.mariadb.mysql_password}}
        volumeMounts:
          - name: wordpress-html
            mountPath: /var/www/html/wp-content/uploads
      volumes:
        - name: wordpress-html
          persistentVolumeClaim:
            claimName: wordpress-pvc
