apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: {{.Values.wordpress.replicas}}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: {{.Values.wordpress.image.repository}}:{{.Values.wordpress.image.tag}}
        imagePullPolicy: {{.Values.wordpress.imagePullPolicy}}
        ports:
        - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: {{.Values.wordpress.wp_db_host}}
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: secrets-mysql
                key : mysql_database
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: secrets-mysql
                key : mysql_user
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets-mysql
                key : mysql_password
          - name : WORDPRESS_CONFIG_EXTRA
            value : 
              define('WP_HOME','http://{{.Values.wordpress.host}}');
              define('WP_SITEURL','http://{{.Values.wordpress.host}}');
        volumeMounts:
          - name: wordpress-html
            mountPath: /var/www/html/wp-content/uploads
      volumes:
        - name: wordpress-html
          persistentVolumeClaim:
            claimName: wordpress-pvc
