apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: {{.Values.wordpress.replicas}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: {{.Values.wordpress.image.repository}}:{{.Values.wordpress.image.tag}}
        imagePullPolicy: {{.Values.wordpress.imagePullPolicy}}
        ports:
        - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: {{.Values.wordpress.wp_db_host}}
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: secrets-db-wordpress
                key: mysql_database
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: secrets-db-wordpress
                key: mysql_user
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets-db-wordpress
                key: mysql_password
          - name : WORDPRESS_CONFIG_EXTRA
            value : 
              define('WP_HOME','http://{{.Values.wordpress.host}}');
              define('WP_SITEURL','http://{{.Values.wordpress.host}}');
        volumeMounts:
          - name: wordpress-html
            mountPath: /var/www/html/
      volumes:
        - name: wordpress-html
          persistentVolumeClaim:
            claimName: {{.Release.Namespace}}-efs-wp-claim
      initContainers:
      - name: init-sym-link
        image: ubuntu:focal
        command: ["mkdir", "-p","/var/www/html_filrouge","/filrouge"]
        command: ["ln", "-s", "/var/www/html_filrouge", "/filrouge"]
        command: ["chown", "-R", "www-data:www-data", "/filrouge"]
        volumeMounts:
        - name: wordpress-html
          mountPath: /filrouge
