kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{.Release.Namespace}}-efs-wp-sc
provisioner: efs.csi.aws.com

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Namespace}}-efs-wp-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{.Release.Namespace}}-efs-wp-sc
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Release.Namespace}}-efs-wp-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{.Release.Namespace}}-efs-wp-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{.Values.wordpress.volume_efs_id}}
