kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{.Release.Namespace}}-efs-db-sc
provisioner: efs.csi.aws.com

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Namespace}}-efs-db-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{.Release.Namespace}}-efs-db-sc
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Release.Namespace}}-efs-db-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{.Release.Namespace}}-efs-db-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{.Values.mariadb.volume_efs_id}}

