apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-wordpress
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: wordpress
 minReplicas: {{.Values.wordpress.hpa.min}}
 maxReplicas: {{.Values.wordpress.hpa.max}}
 targetCPUUtilizationPercentage: {{.Values.wordpress.hpa.cpu}}
