apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Namespace}}-ingress
  annotations:
    alb.ingress.kubernetes.io/group.name: {{.Release.Namespace}}-ingress
    alb.ingress.kubernetes.io/load-balancer-name: {{.Release.Namespace}}-ingress
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-3:865528122231:certificate/7df25315-1994-45a7-8995-db5d359a8486
spec:
  ingressClassName : alb
  rules:
    - host: {{.Values.wordpress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-http
                port:
                  number: 80