apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: {{.Values.wordpress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-http
                port:
                  number: 80
