apiVersion: v1
kind: Secret
metadata:
  name: secrets-mysql
type: Opaque
data:
  mysql_root_password: {{ .Values.mariadb.mysql_root_password | b64enc | quote }}
  mysql_database: {{ .Values.mariadb.mysql_database | b64enc | quote }}
  mysql_user: {{ .Values.mariadb.mysql_user | b64enc | quote }}
  mysql_password: {{ .Values.mariadb.mysql_password | b64enc | quote }}
