apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb 
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: {{.Values.mariadb.image.repository}}:{{.Values.mariadb.image.tag}}
        imagePullPolicy: {{.Values.mariadb.imagePullPolicy}}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: secrets-mysql
                key : mysql_root_password
        - name: MYSQL_DATABASE
          valueFrom:
              secretKeyRef:
                name: secrets-mysql
                key : mysql_database
        - name: MYSQL_USER
          valueFrom:
              secretKeyRef:
                name: secrets-mysql
                key : mysql_user
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef:
                name: secrets-mysql
                key : mysql_password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-mysql
        persistentVolumeClaim:
          claimName: mariadb-pvc