wordpress:
  ingress:
    host: filrouge-prod.barnz.cloudns.ph
  replicas: 2
  image:
    repository: wordpress
    tag: 6.4-apache
  wp_db_host: mariadb-service
  hpa:
    min: 2
    max: 5
    cpu: 50
mariadb:
  replicas: 1
  image:
    repository: mariadb
    tag: 11.1
  mysql_root_password: root
  mysql_database: wordpress
  mysql_user: wordpress
  mysql_password: wordpress
  