wordpress:
  host: filrouge-test.barnz.cloudns.ph
  replicas: 1
  image:
    repository: barnz/wordpress-filrouge
    tag: 1.3
  imagePullPolicy: Always
  wp_db_host: mariadb-service
  hpa:
    min: 1
    max: 2
    cpu: 50
mariadb:
  replicas: 1
  image:
    repository: mariadb
    tag: 11.1
  imagePullPolicy: IfNotPresent
  mysql_root_password: root
  mysql_database: wordpress
  mysql_user: wordpress
  mysql_password: wordpress
  
