wordpress:
  host: filrouge-prod.barnz.cloudns.ph
  replicas: 3
  image:
    repository: barnz/wordpress-filrouge
    tag: 1.3
  imagePullPolicy: Always
  wp_db_host: mariadb-service
  volume_efs_id: fs-04658065d9adb6475
  hpa:
    min: 2
    max: 15
    cpu: 50
mariadb:
  replicas: 1
  image:
    repository: mariadb
    tag: 11.1
  imagePullPolicy: IfNotPresent
  mysql_root_password: root
  mysql_database: wordpress
  mysql_user: wordpress
  mysql_password: wordpress
  volume_efs_id: fs-04cb666198976bf84
